### PR TITLE
chore: add disabled settings menu item

### PR DESCRIPTION
**Pull request by javascripto**
## Description

This pull request adds a new settings menu item 

## Preview

| Preview |
| --- |
| Screen Shot 2022-10-16 at 18 13 13 |

### CODE REVIEW

**Comment by rusconn** [comment]
@javascripto thanks for your contribution!

**Review by rusconn — APPROVED** [review]

**Comment by rusconn** [comment]
@javascripto Please `Squash and merge` if you don't mind fewer commits!

**Comment by javascripto** [comment]
> @javascripto Please `Squash and merge` if you don't mind fewer commits!

Hi @rusconn, I think I don't have merge permissions.

**Comment by rusconn** [comment]
> Hi @rusconn, I think I don't have merge permissions.

@javascripto Oh sorry, I'll merge!

**Pull request merged**
